api_platform:
    title: Hello API Platform
    version: 1.0.0
    eager_loading:
        max_joins: 100
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
        jsonld: ["application/ld+json"]
        multipart: ['multipart/form-data']
    error_formats:
        json: ['application/json']
        multipart: ['multipart/form-data']